partidos agrupados
alexxene/entrega_grupal pull request #21
Opened 2024-12-27 18:51 UTC by iraval-01

Primero he agrupado los partidos mediante el uso de la tabla abbrev y election_data con un inner join ( el join es un item obligatorio que hay que realizar entre tablas). He corregido la fecha de los datos de filtración a 2008 y el field date a > 1

2024-12-27 20:07 UTC, IreneH0404 approved these changes

2024-12-29 18:09 UTC, jruizmes requested changes
Iratxe, puedes por favor cambiar resumen a resumen2 para poder comparar los 2 ficheros y chequear si ambos resúmenes son muy diferentes o no?

2024-12-29 18:18 UTC, jruizmes approved these changes

2024-12-29 18:22 UTC, iraval-01 commented
> Iratxe, puedes por favor cambiar resumen a resumen2 para poder comparar los 2 ficheros y chequear si ambos resúmenes son muy diferentes o no?

Ya estaría :P

2025-01-02 18:58 UTC, closed without merging